# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='problems', to='contest.Tag'),
        ),
    ]
