# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20170905_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='division',
            field=models.CharField(choices=[('Div1', 'Div 1'), ('Div2', 'Div 2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50),
        ),
    ]
