# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20170906_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='division',
            field=models.CharField(choices=[('div1', 'Div 1'), ('div2', 'Div 2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50),
        ),
    ]
