# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20170906_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.AddField(
            model_name='contest',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
