# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-09-10 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20170906_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Url1',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='Url2',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='Url3',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='Url4',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='Url5',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50),
        ),
    ]
