# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20170910_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Url2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='Url3',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='Url4',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='Url5',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
