# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20170910_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Url1',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
